image: gitpod/workspace-postgres:latest

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8080
- port: 5432

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- command: pip3 install -r requirements.txt &&
    python3 bin/refresh-inventory.py bjs-inventory.json rd-inventory.json &&
    createdb qmlist &&
    PYTHONPATH=/workspace/qmlist python3 bin/initdb.py bjs-inventory.json rd-inventory.json