import os

#Global
SECRET_KEY = "b4140de8-9ec1-409e-9b92-d4ce1d2218a6"
TEMPLATES_AUTO_RELOAD = True
EXPLAIN_TEMPLATE_LOADING = False

# WTForms
WTF_CSRF_ENABLED = True

# SQLAlchemy
# SQLALCHEMY_DATABASE_URI = "sqlite://"
SQLALCHEMY_DATABASE_URI = os.environ["DB_URL"]
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Security
SECURITY_PASSWORD_HASH = "plaintext"